/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.ejerciciosarchivos;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.Collection;
import java.util.Collections;
import java.util.Comparator;
import java.util.List;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.stream.Collector;
import java.util.stream.Collectors;
import java.util.stream.IntStream;

import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.showMessageDialog;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author "Erick"
 */
public class FrmBuscarPalabra extends javax.swing.JFrame {

    /**
     * Creates new form FrmBuscarPalabra
     */
    public FrmBuscarPalabra() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        lblNombre = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtContenido = new javax.swing.JTextArea();
        btnBuscarPalabra = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Buscar Palabra dentro de Archivo");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jButton1.setText("Ubicación Archivo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Salir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        lblNombre.setText("Ubicación del Archivo");

        txtNombre.setEditable(false);

        txtContenido.setEditable(false);
        txtContenido.setColumns(20);
        txtContenido.setRows(5);
        jScrollPane1.setViewportView(txtContenido);

        btnBuscarPalabra.setText("Buscar");
        btnBuscarPalabra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarPalabraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup().addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 121,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 270,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jScrollPane1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jButton2).addComponent(jButton1).addComponent(btnBuscarPalabra))
                        .addGap(55, 55, 55)));
        layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout
                .createSequentialGroup().addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup().addComponent(jButton1).addGap(35, 35, 35)
                                .addComponent(btnBuscarPalabra)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton2))
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblNombre))
                                .addGap(18, 18, 18).addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(42, Short.MAX_VALUE)));

        getAccessibleContext().setAccessibleDescription("");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton1ActionPerformed

        JFileChooser seleccion = new JFileChooser();
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("Archivos de textos", "txt", "dat");
        seleccion.setFileFilter(filtro);
        int returnVol = seleccion.showOpenDialog(this);
        if (returnVol == JFileChooser.APPROVE_OPTION) {
            nombreArchivo = seleccion.getSelectedFile().getAbsolutePath();
            txtNombre.setText(nombreArchivo);
        } else {
            showMessageDialog(this, nombreArchivo + " Es un directorio", " Error", 0);
        }

    }// GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton2ActionPerformed
        System.exit(0);
    }// GEN-LAST:event_jButton2ActionPerformed

    // Expresion lambda
    // lista.stream().forEach((var c) -> {
    // int posi = c.indexOf(palabra);
    // if (posi != -1) {
    // System.out.println("Se encontró la palabra, en la posición : " + posi);
    // }
    // });
    // Mostrar linea donde aparece la palabra
    // lista.stream().filter((string) ->
    // string.contains(palabra)).forEach(System.out::println);
    // Mostrar por medio del path posicion
    // String path = Files.readString(Path.of("D:/Archivos/Prueba1/archivo1.txt"));
    // path.lines().forEach((var b) -> {
    // int indexOf = b.indexOf(palabra);
    // if (indexOf != -1) {
    // System.out.println("La palabra se encontró en la posición : " + indexOf);
    // }
    // });
    // Mostrar linea donde aparece la palabra
    // path.lines().filter(predicate -> predicate.indexOf("java") !=
    // -1).forEach(System.out::println);
    String reves = "";

    private void btnBuscarPalabraActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnBuscarPalabraActionPerformed
        String npalabra = JOptionPane.showInputDialog("Ingresar palabra a buscar");
        String palabra = npalabra.replaceAll("/", " ");
        Path path = Path.of(nombreArchivo);
        int pos = -1;

        try {

            List<String> lista = Files.readAllLines(path);
            // lista.forEach((lista1) -> {
            // for (int i = lista1.length() - 1; i >= 0; i--) {
            // reves += lista1.substring(i,i+1);
            // }
            // System.out.println(reves);
            // });

            String cad = "";
            for (int i = 0; i < lista.size(); i++) {
                pos = lista.get(i).indexOf(palabra);
                if (pos != -1) {
                    cad += "Se encontró la palabra en la línea " + i + " posición " + pos + "\n";
                }
            }
            
            txtContenido.setText("Dato a buscar : " + npalabra + "\n" + cad);
            //
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }// GEN-LAST:event_btnBuscarPalabraActionPerformed

    /**
     * @param args the command line arguments
     */

    public static void main(String[] args) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmBuscarPalabra.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmBuscarPalabra.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmBuscarPalabra.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmBuscarPalabra.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmBuscarPalabra().setVisible(true);
            }
        });
    }

    String nombreArchivo;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarPalabra;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JTextArea txtContenido;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
